from dataclasses import dataclass

@dataclass(frozen=True)
class AppTarget:
    app: str
    website: str
    category: str

APPS = [
    AppTarget('Salesforce', 'https://www.salesforce.com/', 'CRM and Sales'),
    AppTarget('HubSpot', 'https://hubspot.com/', 'CRM and Sales'),
    AppTarget('Pipedrive', 'https://pipedrive.com/', 'CRM and Sales'),
    AppTarget('Attio', 'https://attio.com/', 'CRM and Sales'),
    AppTarget('Twenty', 'https://twenty.com/', 'CRM and Sales'),
    AppTarget('Podio', 'https://podio.com/', 'CRM and Sales'),
    AppTarget('Zoho CRM', 'https://zoho.com/crm', 'CRM and Sales'),
    AppTarget('Close', 'https://close.com/', 'CRM and Sales'),
    AppTarget('Copper', 'https://copper.com/', 'CRM and Sales'),
    AppTarget('DealCloud', 'https://api.docs.dealcloud.com/', 'CRM and Sales'),
    AppTarget('Zendesk', 'https://zendesk.com/', 'Support and Helpdesk'),
    AppTarget('Intercom', 'https://intercom.com/', 'Support and Helpdesk'),
    AppTarget('Freshdesk', 'https://freshdesk.com/', 'Support and Helpdesk'),
    AppTarget('Front', 'https://front.com/', 'Support and Helpdesk'),
    AppTarget('Pylon', 'https://usepylon.com/', 'Support and Helpdesk'),
    AppTarget('LiveAgent', 'https://liveagent.com/', 'Support and Helpdesk'),
    AppTarget('Plain', 'https://plain.com/', 'Support and Helpdesk'),
    AppTarget('Help Scout', 'https://helpscout.com/', 'Support and Helpdesk'),
    AppTarget('Gorgias', 'https://gorgias.com/', 'Support and Helpdesk'),
    AppTarget('Gladly', 'https://gladly.com/', 'Support and Helpdesk'),
    AppTarget('Slack', 'https://slack.com/', 'Communications and Messaging'),
    AppTarget('Twilio', 'https://twilio.com/', 'Communications and Messaging'),
    AppTarget('Zoho Cliq', 'https://zoho.com/cliq', 'Communications and Messaging'),
    AppTarget('Lark (Larksuite)', 'https://open.larksuite.com/', 'Communications and Messaging'),
    AppTarget('Pumble', 'https://pumble.com/', 'Communications and Messaging'),
    AppTarget('Discord', 'https://discord.com/', 'Communications and Messaging'),
    AppTarget('Telegram', 'https://core.telegram.org/', 'Communications and Messaging'),
    AppTarget('WhatsApp Business', 'https://developers.facebook.com/docs/whatsapp', 'Communications and Messaging'),
    AppTarget('Aircall', 'https://aircall.io/', 'Communications and Messaging'),
    AppTarget('Vonage', 'https://developer.vonage.com/', 'Communications and Messaging'),
    AppTarget('Google Ads', 'https://developers.google.com/google-ads', 'Marketing, Ads, Email and Social'),
    AppTarget('Meta Ads', 'https://developers.facebook.com/docs/marketing-apis', 'Marketing, Ads, Email and Social'),
    AppTarget('LinkedIn Ads', 'https://learn.microsoft.com/linkedin/marketing', 'Marketing, Ads, Email and Social'),
    AppTarget('GoHighLevel', 'https://highlevel.stoplight.io/', 'Marketing, Ads, Email and Social'),
    AppTarget('Mailchimp', 'https://mailchimp.com/developer', 'Marketing, Ads, Email and Social'),
    AppTarget('Klaviyo', 'https://developers.klaviyo.com/', 'Marketing, Ads, Email and Social'),
    AppTarget('systeme.io', 'https://systeme.io/', 'Marketing, Ads, Email and Social'),
    AppTarget('Pinterest', 'https://developers.pinterest.com/', 'Marketing, Ads, Email and Social'),
    AppTarget('Threads (Meta)', 'https://developers.facebook.com/docs/threads', 'Marketing, Ads, Email and Social'),
    AppTarget('SendGrid', 'https://sendgrid.com/', 'Marketing, Ads, Email and Social'),
    AppTarget('Shopify', 'https://shopify.dev/', 'Ecommerce'),
    AppTarget('WooCommerce', 'https://woocommerce.com/document/woocommerce-rest-api', 'Ecommerce'),
    AppTarget('BigCommerce', 'https://developer.bigcommerce.com/', 'Ecommerce'),
    AppTarget('Salesforce Commerce Cloud', 'https://developer.salesforce.com/docs/commerce', 'Ecommerce'),
    AppTarget('Magento (Adobe Commerce)', 'https://developer.adobe.com/commerce', 'Ecommerce'),
    AppTarget('Squarespace', 'https://developers.squarespace.com/', 'Ecommerce'),
    AppTarget('Ecwid', 'https://api-docs.ecwid.com/', 'Ecommerce'),
    AppTarget('Gumroad', 'https://gumroad.com/api', 'Ecommerce'),
    AppTarget('Amazon Selling Partner', 'https://developer-docs.amazon.com/sp-api', 'Ecommerce'),
    AppTarget('fanbasis', 'https://fanbasis.com/', 'Ecommerce'),
    AppTarget('DataForSEO', 'https://docs.dataforseo.com/', 'Data, SEO and Scraping'),
    AppTarget('SE Ranking', 'https://seranking.com/api', 'Data, SEO and Scraping'),
    AppTarget('Ahrefs', 'https://ahrefs.com/api', 'Data, SEO and Scraping'),
    AppTarget('MrScraper', 'https://docs.mrscraper.com/', 'Data, SEO and Scraping'),
    AppTarget('Apify', 'https://docs.apify.com/', 'Data, SEO and Scraping'),
    AppTarget('Firecrawl', 'https://firecrawl.dev/', 'Data, SEO and Scraping'),
    AppTarget('Bright Data', 'https://brightdata.com/', 'Data, SEO and Scraping'),
    AppTarget('Sherlock', 'https://github.com/sherlock-project/sherlock', 'Data, SEO and Scraping'),
    AppTarget('Waterfall.io', 'https://waterfall.io/', 'Data, SEO and Scraping'),
    AppTarget('Clay', 'https://clay.com/', 'Data, SEO and Scraping'),
    AppTarget('GitHub', 'https://docs.github.com/rest', 'Developer, Infra and Data platforms'),
    AppTarget('Vercel', 'https://vercel.com/docs/rest-api', 'Developer, Infra and Data platforms'),
    AppTarget('Netlify', 'https://docs.netlify.com/api', 'Developer, Infra and Data platforms'),
    AppTarget('Cloudflare', 'https://developers.cloudflare.com/api', 'Developer, Infra and Data platforms'),
    AppTarget('Supabase', 'https://supabase.com/docs', 'Developer, Infra and Data platforms'),
    AppTarget('Neo4j', 'https://neo4j.com/docs/api', 'Developer, Infra and Data platforms'),
    AppTarget('Snowflake', 'https://docs.snowflake.com/', 'Developer, Infra and Data platforms'),
    AppTarget('MongoDB Atlas', 'https://mongodb.com/docs/atlas/api', 'Developer, Infra and Data platforms'),
    AppTarget('Datadog', 'https://docs.datadoghq.com/api', 'Developer, Infra and Data platforms'),
    AppTarget('Sentry', 'https://docs.sentry.io/api', 'Developer, Infra and Data platforms'),
    AppTarget('Notion', 'https://developers.notion.com/', 'Productivity and Project Management'),
    AppTarget('Airtable', 'https://airtable.com/developers', 'Productivity and Project Management'),
    AppTarget('Linear', 'https://developers.linear.app/', 'Productivity and Project Management'),
    AppTarget('Jira', 'https://developer.atlassian.com/', 'Productivity and Project Management'),
    AppTarget('Asana', 'https://developers.asana.com/', 'Productivity and Project Management'),
    AppTarget('Monday.com', 'https://developer.monday.com/', 'Productivity and Project Management'),
    AppTarget('ClickUp', 'https://clickup.com/api', 'Productivity and Project Management'),
    AppTarget('Coda', 'https://coda.io/developers', 'Productivity and Project Management'),
    AppTarget('Smartsheet', 'https://smartsheet.com/developers', 'Productivity and Project Management'),
    AppTarget('Harvest', 'https://help.getharvest.com/api-v2', 'Productivity and Project Management'),
    AppTarget('Stripe', 'https://stripe.com/docs/api', 'Finance and Fintech'),
    AppTarget('Plaid', 'https://plaid.com/docs', 'Finance and Fintech'),
    AppTarget('Binance', 'https://binance-docs.github.io/', 'Finance and Fintech'),
    AppTarget('Paygent Connect', 'https://www.paygent.co.jp/', 'Finance and Fintech'),
    AppTarget('iPayX', 'https://ipayx.ai/docs', 'Finance and Fintech'),
    AppTarget('QuickBooks', 'https://developer.intuit.com/', 'Finance and Fintech'),
    AppTarget('Xero', 'https://developer.xero.com/', 'Finance and Fintech'),
    AppTarget('Brex', 'https://developer.brex.com/', 'Finance and Fintech'),
    AppTarget('Ramp', 'https://docs.ramp.com/', 'Finance and Fintech'),
    AppTarget('PitchBook', 'https://pitchbook.com/', 'Finance and Fintech'),
    AppTarget('NotebookLM', 'https://cloud.google.com/gemini', 'AI, Research and Media-native'),
    AppTarget('Otter AI', 'https://help.otter.ai/', 'AI, Research and Media-native'),
    AppTarget('Fathom', 'https://fathom.video/', 'AI, Research and Media-native'),
    AppTarget('Consensus', 'https://consensus.app/', 'AI, Research and Media-native'),
    AppTarget('Reducto', 'https://reducto.ai/', 'AI, Research and Media-native'),
    AppTarget('Devin', 'https://docs.devin.ai/', 'AI, Research and Media-native'),
    AppTarget('higgsfield', 'https://higgsfield.ai/cli', 'AI, Research and Media-native'),
    AppTarget('Mermaid CLI', 'https://github.com/mermaid-js/mermaid-cli', 'AI, Research and Media-native'),
    AppTarget('YouTube Transcript', 'https://transcriptapi.com/', 'AI, Research and Media-native'),
    AppTarget('Grain', 'https://grain.com/', 'AI, Research and Media-native'),
]

assert len(APPS) == 100